# Generated by Django 5.1.3 on 2024-11-28 18:33

import file.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=15)),
                (
                    "Mobile_no",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "Profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to=file.models.upload_path
                    ),
                ),
            ],
        ),
    ]
