# Generated by Django 5.1.3 on 2024-12-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0002_alter_profile_mobile_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="Mobile_no",
            new_name="mobile_no",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="Profile_photo",
            new_name="profile_photo",
        ),
    ]
