# Generated by Django 5.1.3 on 2024-12-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0005_alter_profile_address_alter_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
