# Generated by Django 5.1.3 on 2024-12-26 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("file", "0006_alter_profile_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employeeprofile",
            fields=[
                ("empId", models.AutoField(primary_key=True, serialize=False)),
                ("empName", models.CharField(max_length=15, null=True)),
                ("empCode", models.CharField(max_length=15, null=True)),
                ("empEmailId", models.CharField(max_length=255, null=True)),
                ("empDesignation", models.CharField(max_length=15, null=True)),
                ("role", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "ClientProjectId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("projectName", models.CharField(max_length=255, null=True)),
                ("startDate", models.DateField()),
                ("ExceptedEnddate", models.DateField()),
                ("completedDate", models.DateField()),
                ("contactPerson", models.CharField(max_length=255, null=True)),
                ("contactPersonPhoneno", models.CharField(max_length=255, null=True)),
                ("totalEmpWorking", models.CharField(max_length=255, null=True)),
                ("projectCost", models.IntegerField()),
                ("projectDetails", models.CharField(max_length=255, null=True)),
                ("contactPersonEmailId", models.CharField(max_length=255, null=True)),
                (
                    "clientId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="file.profile"
                    ),
                ),
                (
                    "leadByEmpId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Employee.employeeprofile",
                    ),
                ),
            ],
        ),
    ]
