# Generated by Django 5.1.3 on 2024-12-27 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0001_initial"),
        ("file", "0006_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttask",
            name="clientId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client",
                to="file.profile",
            ),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="completedDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="leadByEmpId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead",
                to="Employee.employeeprofile",
            ),
        ),
    ]
