# Generated by Django 5.1.3 on 2024-12-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Employee", "0002_alter_projecttask_clientid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projecttask",
            name="completedDate",
        ),
    ]
